site_name: Apache Kafka Studies
repo_url: https://github.com/jbcodeforce/kafka-studies.git
nav:
  - Introduction: index.md
  - Apache Kafka summary: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/readme
  - Consumer practices: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/consumers
  - Producer practices: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/producers
  - Kafka streaming notes: kstreams.md
  - Kafka with Python: python.md
  - Strimzi deployment: strimzi-deploy.md
  - Mirror Maker 2.0: mirrormaker.md
  - Monitoring with Kafka: monitoring.md
  - Kafka FAQ: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/FAQ
  - Kafka Connect: https://ibm-cloud-architecture.github.io/refarch-eda/kafka/connect
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences